export const PRODUCT_CATEGORIES = 'PRODUCT_CATEGORIES'
export const MENU = 'MENU'

export const PRODUCT = 'PRODUCT'

export const ADD_CART_TO_ITEM = 'ADD_CART_TO_ITEM'

export const FILTER_PRODUCT = 'FILTER_PRODUCT'
export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM'
